---
- name: Stop and uninstall quota and quotatool
  tasks:

    - name: Quota stopped
      service:
        name: quota
        state: stopped

    - name: Packages quota and quotatool absent
      apt:
        pkg:
          - quota
          - quotatool
        state: absent
        autoclean: true
        autoremove: true

  tags:
    - quota
...
