---
- name: Enable and configue quotas using aquota
  block:

    - name: "{{ quota_device }}:{{ quota_name }} present in /etc/quotatab"
      ansible.builtin.lineinfile:
        dest: /etc/quotatab
        line: "{{ quota_device }}:{{ quota_name }}"
        state: present
      notify: Restart quota

    - name: "Touch {{ quota_dir }}/aquota.user"
      ansible.builtin.file:
        path: "{{ quota_dir }}/aquota.user"
        state: touch
        access_time: preserve
        modification_time: preserve
        owner: root
        group: root
        mode: 0600
      notify: Restart quota

    - name: Quota enabled and running
      ansible.builtin.service:
        name: quota
        state: started

    - name: "Run quotaon {{ quota_dir }}"
      ansible.builtin.command: "quotaon {{ quota_dir }}"
      register: quota_quotaon
      when: not quota_enabled
      failed_when: ( "Cannot find filesystem to check or filesystem not mounted with quota option" in quota_quotaon.stdout )

    - name: "Set the gracetimes for {{ quota_dir | default('/home') }}"
      ansible.builtin.command: "setquota -t {{ quota_grace_block }} {{ quota_grace_inode }} {{ quota_dir }}"
      when: ( (quota_existing_grace_block | int) != (quota_grace_block | int) ) or ( (quota_existing_grace_inode | int) != (quota_grace_inode | int) )

    - name: Quota warning config in place
      ansible.builtin.template:
        src: warnquota.conf.j2
        dest: /etc/warnquota.conf

    - name: Quota warning defaults in place
      ansible.builtin.template:
        src: quota.j2
        dest: /etc/default/quota

    - name: Warn that a reboot might be needed
      ansible.builtin.debug:
        msg: "You might need to reboot this server before the disk quotas are applied"
      when: quota_installed.changed

  tags:
    - quota
...
