---
- name: Enable repquota output to be reported in ansible_local facts
  block:

    - name: Ansible facts.d directory present
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        recurse: true
        state: directory
        mode: 0700
        owner: root
        group: root

    # https://stackoverflow.com/a/10645490
    - name: XSLT stylesheet present
      ansible.builtin.copy:
        src: attributetoelement.xslt
        dest: /etc/ansible/attributetoelement.xslt
        mode: 0644
        owner: root
        group: root

    - name: repquota wrapper present
      ansible.builtin.template:
        src: repquota.fact.j2
        dest: /etc/ansible/facts.d/repquota.fact
        mode: 0700
        owner: root
        group: root

  tags:
    - quota
...
