---
- name: Journaled usrquota
  block:

    - name: Move the aquota.user file if it exists to /root/aquota.user.bak
      ansible.builtin.command: "mv {{ quota_dir }}/aquota.user /root/aquota.user.bak"
      changed_when: true
      when: quota_aquota_users_file.stat.exists | bool

    - name: Manual intervention needed to upgrade ext2 to ext4
      ansible.builtin.fail:
        msg:
          - "Please manually unmount the {{ quota_dir }} directory (stop services that run from it, unmount things mounted on it etc) and then run:"
          - "tune2fs -O extents,uninit_bg,dir_index,has_journal {{ quota_device }}"
          - "e2fsck -pf {{ quota_device }}"
          - "Then reboot the server and re-run this role."
      when: quota_device_fstype == "ext2"

    - name: Manual intervention needed to upgrade ext3 to ext4
      ansible.builtin.fail:
        msg:
          - "Please manually unmount the {{ quota_dir }} directory (stop services that run from it, unmount things mounted on it etc) and then run:"
          - "tune2fs -O extents,uninit_bg,dir_index {{ quota_device }}"
          - "e2fsck -pf {{ quota_device }}"
          - "Then reboot the server and re-run this role."
      when: quota_device_fstype == "ext3"

    - name: Manual intervention needed to enable journaled usrquota
      ansible.builtin.fail:
        msg:
          - "Please manually unmount the {{ quota_dir }} directory (stop services that run from it, unmount things mounted on it etc) and then run:"
          - "tune2fs -O quota {{ quota_device }}"
          - "Then reboot the server and re-run this role and also re-run the tasks to set the quotas as they need resetting when switching from aquota to journald."
      when: ("quota" not in quota_device_features)

  tags:
    - quota
    - quota_journald
...
