---
- name: Check that the quota_dir directory is on a partition
  command: "mountpoint {{ quota_dir | default('/home') }}"
  register: quota_dir_mountpoint

- name: Get the partition filesystem
  shell: "df -P {{ quota_dir | default('/home') }} | tail -1 | awk '{ print $1 }'"
  register: quota_filesystem

- name: Get the mount options
  shell: "cat /proc/mounts | egrep '[[:space:]]{{ quota_dir | default('/home') }}[[:space:]]' | awk '{ print $4 }'" 
  register: quota_mount_options
  failed_when: '"quota" not in quota_mount_options.stdout'

- name: Quota and quotatool present
  apt:
    pkg:
      - quota
      - quotatool
    state: present
    update_cache: true
  register: quota_installed

- name: quota_dir listed in /etc/quotatab 
  lineinfile:
    dest: /etc/quotatab
    line: "{{ quota_filesystem.stdout }}:{{ quota_dir_name | default('home') }}"
    state: present

- name: Quota on
  command: "quotaon {{ quota_dir | default('/home') }}"
  register: quota_quotaon
  when: quota_installed.changed
  failed_when: '"Cannot find filesystem to check or filesystem not mounted with quota option" in quota_quotaon.stdout'

- name: Quota warning config in place
  template:
    src: templates/warnquota.conf.j2
    dest: /etc/warnquota.conf
    backup: true

- name: Quota check
  command: "quotaon -pu {{ quota_dir | default('/home') }}"
  register: quota_check
  failed_when: '"user quota on" not in quota_check.stdout'

- name: Warn that a reboot might be needed
  debug:
    msg: "You might need to reboot this server before the disk quotas are applied"
  when: quota_installed.changed
