---
- name: Include quota requirements
  ansible.builtin.include_tasks: requirements.yml
  tags:
    - quota
    - quota_req

- name: Include quota local fact tasks
  ansible.builtin.include_tasks: local_facts.yml
  tags:
    - quota
    - quota_local_facts
    - quota_req

- name: Include quota check tasks
  ansible.builtin.include_tasks: checks.yml
  when: (quota is defined) and (quota | bool)
  tags:
    - quota
    - quota_check

- name: Configure quota tasks
  block:

    - name: Include journaled tasks for Debian Bullseye
      ansible.builtin.include_tasks: journaled.yml
      when: ansible_distribution_major_version is version('11', '>=')

    - name: Include aquota tasks for Debian Buster and Stretch
      ansible.builtin.include_tasks: aquota.yml
      when: ansible_distribution_major_version is version('11', '<')

  when: (quota is defined) and (quota | bool)
  tags:
    - quota
...
