---
- name: Include quota requirements
  ansible.builtin.include_tasks: requirements.yml
  tags:
    - quota
    - quota_req

- name: Include quota check tasks
  ansible.builtin.include_tasks: checks.yml
  when: (quota is defined) and (quota | bool)
  tags:
    - quota
    - quota_check

- name: Configure quota tasks
  block:

    - name: Include journaled tasks for Debian Bullseye and greater when aquota is not is use
      ansible.builtin.include_tasks: journaled.yml
      when:
        - ansible_distribution_major_version is version('11', '>=')
        - quota_type is defined
        - quota_type == "journaled"

    - name: Include aquota tasks for Debian Buster and Stretch or when aquota is in use or when quotas are not configured
      ansible.builtin.include_tasks: aquota.yml
      when: >-
        (ansible_distribution_major_version is version('11', '<'))
        or ((quota_type is defined) and (quota_type == "aquota"))
        or (quota_type is not defined)

  when: (quota is defined) and (quota | bool)
  tags:
    - quota
...
