---
- name: Install and enable or uninstall quota and quotatool
  tasks:

    - name: Packages quota and quotatool installed and enabled
      include_tasks: enabled.yml
      when: quota

    - name: Packages quota and quotatool absent
      apt:
        pkg:
          - quota
          - quotatool
        state: absent
      when: not quota

  when: quota is defined
  tags:
    - quota
...
