---
- name: Enable and configue quotas
  block:

    - name: Include journaled tasks for Debian Bullseye and greater when aquota is not is use
      include_tasks: journaled.yml
      when:
        - ( ansible_distribution_major_version is version('11', '>=') )
        - ( quota_type is not defined ) or ( quota_type == "journaled" )

    - name: Include aquota tasks for Debian Buster and Stretch of when aquota is in use
      include_tasks: aquota.yml
      when: ( ansible_distribution_major_version is version('11', '<') ) or ( (  quota_type is defined ) and ( quota_type == "aquota" ) )

    - name: "{{ {{ quota_filesystem }}:{{ quota_dir_name }} present in /etc/quotatab"
      lineinfile:
        dest: /etc/quotatab
        line: "{{ quota_filesystem }}:{{ quota_dir_name }}"
        state: present
      notify: Restart quota

    - name: Quota enabled and running
      service:
        name: quota
        state: started

    - name: "quotaon check {{ quota_dir }}"
      command: "quotaon -vpu {{ quota_dir }}"
      changed_when: false
      register: quota_check

    - name: "quotaon {{ quota_dir | default('/home') }}"
      command: "quotaon {{ quota_dir | default('/home') }}"
      register: quota_quotaon
      when: '"is off" in quota_check.stdout'
      failed_when: '"Cannot find filesystem to check or filesystem not mounted with quota option" in quota_quotaon.stdout'

    - name: "quotaon check {{ quota_dir | default('/home') }}"
      command: "quotaon -pu {{ quota_dir | default('/home') }}"
      ignore_errors: true
      register: quota_check
      when: quota_quotaon.changed
      changed_when: '"is on" not in quota_check.stdout'
      failed_when: '"is off" in quota_quotaon.stdout'

    - name: "Read the grace times for {{ quota_dir | default('/home') }}"
      shell: "repquota {{ quota_dir | default('/home') }} | grep '^Block'"
      register: quota_grace_times_before
      changed_when: false

    - name: "Set the gracetimes for {{ quota_dir | default('/home') }}"
      shell: "setquota -t {{ quota_grace_block | default('86400') }} {{ quota_grace_inode | default('86400') }} {{ quota_dir | default('/home') }} ; repquota {{ quota_dir | default('/home') }} | grep '^Block'"
      register: quota_grace_times_after
      changed_when: quota_grace_times_before.stdout != quota_grace_times_after.stdout

    - name: Quota warning config in place
      template:
        src: warnquota.conf.j2
        dest: /etc/warnquota.conf

    - name: Quota warning defaults in place
      template:
        src: quota.j2
        dest: /etc/default/quota

    - name: Warn that a reboot might be needed
      debug:
        msg: "You might need to reboot this server before the disk quotas are applied"
      when: quota_installed.changed

  tags:
    - quota
...
