---
- name: Requirements
  block:

    # Packages and directories are not removed when not quota in case other things depend on them
    - name: Packages directories and files present when quota
      block:

        - name: Required packages present
          apt:
            pkg:
              - jq
              - python3-pip
              - python3-setuptools
              - quota
              - quotatool
              - xsltproc
            state: present
            autoclean: true
            autoremove: true

        - name: Python yq present
          pip:
            name: yq
            state: present

        - name: Ansible facts.d directory present
          ansible.builtin.file:
            path: /etc/ansible/facts.d
            state: directory
            recurse: true
            mode: 0700
            owner: root
            group: root

        - name: repquota wrapper present
          ansible.builtin.template:
            src: repquota.fact.j2
            dest: /etc/ansible/facts.d/repquota.fact
            mode: 0700
            owner: root
            group: root

        - name: XSLT stylesheet present
          ansible.builtin.copy:
            src: attributetoelement.xslt
            dest: /etc/ansible/attributetoelement.xslt
            mode: 0644
            owner: root
            group: root

      when: quota

    - name: Files absent when not quota
      file:
        path: "{{ path }}"
        state: absent
      loop:
        - /etc/ansible/attributetoelement.xslt
        - /etc/ansible/facts.d/repquota.fact
      loop_control:
        loop_var: path
        label: "{{ path | basename }}"
      when: not quota

  tags:
    - quota
...
