---
- name: Packages present when quota
  ansible.builtin.apt:
    pkg:
      - jo
      - quota
      - quotatool
    state: present
  when: quota | bool
  tags:
    - quota
    - quota_req

- name: Packages absent when not quota
  ansible.builtin.apt:
    pkg:
      - quota
      - quotatool
    state: absent
    autoclean: true
    autoremove: true
  when: not quota | bool
  tags:
    - quota
    - quota_req
...
