---
- name: Requirements
  block:

    # Packages and directories are not removed when not quota in case other things depend on them
    - name: Packages directories and files present when quota
      block:

        - name: Required packages present
          apt:
            pkg:
              - jc
              - quota
              - quotatool
            state: present
            autoclean: true
            autoremove: true

        - name: Ansible facts.d directory present
          ansible.builtin.file:
            path: /etc/ansible/facts.d
            state: directory
            recurse: true
            mode: 0700
            owner: root
            group: root

        - name: Ansible local facts repquota script present
          ansible.builtin.template:
            src: repquota.fact.j2
            dest: /etc/ansible/facts.d/repquota.fact
            mode: 0700
            owner: root
            group: root

      when: quota

    - name: Ansible local facts repquota script absent when not quota
      file:
        path: /etc/ansible/facts.d/repquota.fact
        state: absent
      when: not quota

  tags:
    - quota
...
